version: '3.1'

services:
    server:
        image: jetbrains/teamcity-server:2017.2.3
        volumes:
            - data:/data/teamcity_server/datadir
            - logs:/opt/teamcity/logs
        ports:
            - 8011:8111
        restart: unless-stopped
        networks:
            - net

    agent:
        image: jetbrains/teamcity-agent:2017.2.3
        volumes:
            - npipe:////./pipe/docker_engine:/var/run/docker.sock
        environment:
            SERVER_URL: http://server:8111
        restart: unless-stopped
        networks:
            - net

volumes:
    data:
    logs:

networks: 
    net: