version: '3.1'

services:
  host:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
    ports:
      - 8009:9200
    volumes:
      - data:/usr/share/elasticsearch/data
    networks:
      - net
    restart: unless-stopped
  
  dejavu:
    image: appbaseio/dejavu
    ports:
      - 8010:1358
    networks:
      - net
    restart: unless-stopped

volumes:
    data:

networks:
  net: