version: '3.1'

services:
    db:
        image: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
            - C://docker//buckups:/var/lib/postgresql/backups
        ports:
            - 8002:5432
        environment:
            - POSTGRES_PASSWORD=givemedata
        restart: unless-stopped
        networks:
            - net

    admin:
        image: dpage/pgadmin4
        volumes:
            - admin-data:/var/lib/pgadmin
            - C://docker//buckups:/var/lib/pgadmin/storage/admin/backups
        ports:
            - 8003:80
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin
            - PGADMIN_DEFAULT_PASSWORD=admin
        restart: unless-stopped
        networks:
            - net

volumes:
    db-data:
    admin-data:

networks: 
    net: